ren c0_01.png RED_ONE.png
ren c0_02.png RED_TWO.png
ren c0_03.png RED_THREE.png
ren c0_04.png RED_FOUR.png
ren c0_05.png RED_FIVE.png
ren c0_06.png RED_SIX.png
ren c0_07.png RED_SEVEN.png
ren c0_08.png RED_EIGHT.png
ren c0_09.png RED_NINE.png
ren c0_10.png RED_SKIP.png
ren c0_11.png RED_REVERSE.png
ren c0_12.png RED_DRAWTWO.png
ren c1_01.png ORANGE_ONE.png
ren c1_02.png ORANGE_TWO.png
ren c1_03.png ORANGE_THREE.png
ren c1_04.png ORANGE_FOUR.png
ren c1_05.png ORANGE_FIVE.png
ren c1_06.png ORANGE_SIX.png
ren c1_07.png ORANGE_SEVEN.png
ren c1_08.png ORANGE_EIGHT.png
ren c1_09.png ORANGE_NINE.png
ren c1_10.png ORANGE_SKIP.png
ren c1_11.png ORANGE_REVERSE.png
ren c1_12.png ORANGE_DRAWTWO.png
ren c2_01.png GREEN_ONE.png
ren c2_02.png GREEN_TWO.png
ren c2_03.png GREEN_THREE.png
ren c2_04.png GREEN_FOUR.png
ren c2_05.png GREEN_FIVE.png
ren c2_06.png GREEN_SIX.png
ren c2_07.png GREEN_SEVEN.png
ren c2_08.png GREEN_EIGHT.png
ren c2_09.png GREEN_NINE.png
ren c2_10.png GREEN_SKIP.png
ren c2_11.png GREEN_REVERSE.png
ren c2_12.png GREEN_DRAWTWO.png
ren c3_01.png BLUE_ONE.png
ren c3_02.png BLUE_TWO.png
ren c3_03.png BLUE_THREE.png
ren c3_04.png BLUE_FOUR.png
ren c3_05.png BLUE_FIVE.png
ren c3_06.png BLUE_SIX.png
ren c3_07.png BLUE_SEVEN.png
ren c3_08.png BLUE_EIGHT.png
ren c3_09.png BLUE_NINE.png
ren c3_10.png BLUE_SKIP.png
ren c3_11.png BLUE_REVERSE.png
ren c3_12.png BLUE_DRAWTWO.png
ren c0_00.png RED_ZERO.png
ren c1_00.png ORANGE_ZERO.png
ren c2_00.png GREEN_ZERO.png
ren c3_00.png BLUE_ZERO.png
ren c4_00.png WILDCARD_AnyColor.png
ren c4_01.png WILDCARD_DRAWFOUR.png

pause
